//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus_reference
    {
        public int id { get; set; }
        public byte from_station_id { get; set; }
        public byte to_station_id { get; set; }
        public System.TimeSpan duration { get; set; }
        public System.DateTime interval_time { get; set; }
    }
}
