//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class bus_simulation
    {
        public int id { get; set; }
        public short bus_id { get; set; }
        public int last_check_in { get; set; }
        public System.DateTime measurement_timestamp { get; set; }
    }
}
