//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bus_dbEntities : DbContext
    {
        public bus_dbEntities()
            : base("name=bus_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bus> bus { get; set; }
        public virtual DbSet<bus_data> bus_data { get; set; }
        public virtual DbSet<bus_driver_data> bus_driver_data { get; set; }
        public virtual DbSet<bus_measurement> bus_measurement { get; set; }
        public virtual DbSet<bus_position> bus_position { get; set; }
        public virtual DbSet<bus_reference> bus_reference { get; set; }
        public virtual DbSet<bus_simulation> bus_simulation { get; set; }
        public virtual DbSet<bus_trace> bus_trace { get; set; }
        public virtual DbSet<car_data> car_data { get; set; }
        public virtual DbSet<course_data> course_data { get; set; }
        public virtual DbSet<line> line { get; set; }
        public virtual DbSet<line_trace> line_trace { get; set; }
        public virtual DbSet<station> station { get; set; }
        public virtual DbSet<station_on_line> station_on_line { get; set; }
        public virtual DbSet<timetable> timetable { get; set; }
    }
}
