//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class car_data
    {
        public int id { get; set; }
        public short bus_id { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
        public double position_accuracy { get; set; }
        public double speed { get; set; }
        public double speed_accuracy { get; set; }
        public int direction { get; set; }
        public double accel_x { get; set; }
        public double accel_y { get; set; }
        public double accel_z { get; set; }
        public double gyro_x { get; set; }
        public double gyro_y { get; set; }
        public double gyro_z { get; set; }
        public Nullable<int> trace_match { get; set; }
        public System.DateTime measurement_timestamp { get; set; }
    }
}
