//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class line
    {
        public string id { get; set; }
        public string route_name { get; set; }
        public byte start_station_id { get; set; }
        public byte end_station_id { get; set; }
    }
}
