//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeasuredData
    {
        public int ID { get; set; }
        public int From { get; set; }
        public int To { get; set; }
        public int duration { get; set; }
        public System.DateTime dateTime { get; set; }
    }
}
