//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFService
{
    using System;
    using System.Collections.Generic;
    
    public partial class timetable
    {
        public int id { get; set; }
        public string line_id { get; set; }
        public byte station_id { get; set; }
        public string start_time { get; set; }
        public byte weekday_flag { get; set; }
    }
}
